<a href="https://colab.research.google.com/github/Tejasri-Vallakati/cspt_training2026/blob/main/Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df = pd.read_excel('CineMetrics_Dataset.xlsx')
df.head()

,Movie_ID,Title,Genre,Release_Year,Duration_Min,Language,Country,Streaming_Platform,Budget_Million_USD,Revenue_Million_USD,IMDB_Rating,Votes_Thousands,Critic_Score,Director_Experience_Years
0,1,The Crimson Odyssey,Animation,2013,NaN,French,France,HBO Max,33.8,43.9,3.6,315.9,46.0,7.0
1,2,The Sacred Echo,Documentary,2014,88.0,Hindi,India,Prime Video,58.4,183.8,6.6,79.9,NaN,13.0
2,3,The Rising Illusion,Action,1995,105.0,Spanish,Mexico,HBO Max,12.8,13.8,6.8,71.9,32.0,30.0
3,4,The Crimson Awakening,Sci-Fi,2003,107.0,German,Germany,Netflix,11.4,27.8,8.0,74.6,81.0,33.0
4,5,The Last Legacy,Sci-Fi,2020,82.0,Hindi,India,Netflix,37.1,13.1,NaN,26.1,47.0,15.0

In [3]:
df=pd.read_excel("/content/CineMetrics_Dataset.xlsx")
df

,Movie_ID,Title,Genre,Release_Year,Duration_Min,Language,Country,Streaming_Platform,Budget_Million_USD,Revenue_Million_USD,IMDB_Rating,Votes_Thousands,Critic_Score,Director_Experience_Years
0,1,The Crimson Odyssey,Animation,2013,NaN,French,France,HBO Max,33.8,43.9,3.6,315.9,46.0,7.0
1,2,The Sacred Echo,Documentary,2014,88.0,Hindi,India,Prime Video,58.4,183.8,6.6,79.9,NaN,13.0
2,3,The Rising Illusion,Action,1995,105.0,Spanish,Mexico,HBO Max,12.8,13.8,6.8,71.9,32.0,30.0
3,4,The Crimson Awakening,Sci-Fi,2003,107.0,German,Germany,Netflix,11.4,27.8,8.0,74.6,81.0,33.0
4,5,The Last Legacy,Sci-Fi,2020,82.0,Hindi,India,Netflix,37.1,13.1,NaN,26.1,47.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,The Fading Mirage,Romance,2021,141.0,French,France,HBO Max,66.0,173.3,5.0,72.4,44.0,30.0
296,297,The Sacred Journey,Fantasy,2014,110.0,Spanish,Spain,HBO Max,43.2,52.3,3.9,252.4,53.0,32.0
297,298,The Burning Rebellion,Documentary,2006,158.0,Korean,South Korea,HBO Max,114.3,165.6,8.1,126.7,NaN,8.0
298,299,The Fading Descent,Comedy,1999,114.0,Japanese,Japan,HBO Max,188.8,661.6,5.3,132.7,41.0,25.0
299,300,The Eternal Legacy,Romance,2015,148.0,English,USA,HBO Max,9.7,0.0,6.4,121.4,63.0,20.0

In [6]:
df["Duration_Min"] = df["Duration_Min"].fillna(df["Duration_Min"].mean())
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Movie_ID                   300 non-null    int64
 1   Title                      300 non-null    object
 2   Genre                      288 non-null    object
 3   Release_Year               300 non-null    int64
 4   Duration_Min               300 non-null    float64
 5   Language                   291 non-null    object
 6   Country                    300 non-null    object
 7   Streaming_Platform         291 non-null    object
 8   Budget_Million_USD         264 non-null    float64
 9   Revenue_Million_USD        273 non-null    float64
 10  IMDB_Rating                282 non-null    float64
 11  Votes_Thousands            285 non-null    float64
 12  Critic_Score               279 non-null    float64
 13  Director_Experience_Years  288 non-null    float64
dtypes: float64(7), int64(2), object(5)
memory usage: 32.9+ KB